leftnav:
- identifier: d34beadf-ebaa-c907-00bf-5849b8266e37
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: a5f69066-d48b-7c57-e924-c8c1ef66caf9
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: bab550e4-03c6-fc55-77b2-a7ad72ae094d
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: d33bc18e-a222-14f6-db29-92611adebd7e
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: e28ebafa-4ec5-70fa-4882-eccd5ff28636
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
